version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: next_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      YANDEX_WEATHER_API_KEY: 48f8c7a9-9a49-476e-b264-8018859253f5

    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

volumes:
  postgres_data: